#!/usr/bin/env sh

# format codebase in the pre-commit period
mvn spotless:apply

# check code, if invalid then stop committing
mvn spotless:check

exit_code=$?

# check if exit code is 0
if [ $exit_code -eq 0 ]; then
    echo ">>> OK, clean code!"
else
    echo ">>> Something went wrong... stop committing!"
    exit $exit_code
fi

# add all files to stage change
git add .
